name: guide_me
description: "A new Flutter project."

publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  animations: ^2.0.11
  rive: ^0.13.20
  flutter_dotenv: ^5.2.1
  firebase_core: ^3.12.1
  pin_code_fields: ^8.0.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  logger: ^2.5.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.3.0
  mailer: ^6.4.1
  ulid: ^2.0.1
  cloud_functions: ^5.4.0
  random_string: ^2.3.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - mailersend-proxy/.env

